alphagov/verify-local-startup

generate/cfssl-config.json
The is_ca option has changed in newer versions of cfssl than available
in homebrew.  If one follows the instructions in the cfssl wiki to get
the latest version, it cannot generate ocsp responses using this json.
This commit leaves the now ignored deprecated option present and adds
in the replacement.  Tested on macos with both options and it still
works correctly.
The new option is here:
https://github.com/cloudflare/cfssl/blob/d2393674072314fda47d2c7c16cb7fd4cdc16821/doc/cmd/cfssl.txt#L124
A clue for this fix was found here:
https://github.com/cloudflare/cfssl/issues/652#issuecomment-236369401
Pair: WillPa
=> bau: fix newer versions of cfssl

config/ports.env, generate-env.rb
Most consumers of a .env file expect a KEY=VALUE list with no
export statements. Using set +o allexport in bash allows us to
use the normal .env syntax whilst still setting env vars
Authors: @andy-paine
=> BAU: Fix generate-env to produce a proper .env file (no exports)

config/ports.env
Now that we have added the config for generating the signed trust anchor file (see [this PR](https://github.com/alphagov/verify-metadata/pull/69). 
The signed trust anchor for running local stuff are now served up automatically. 
I also cleaned up the environment variables that we no longer use.
=> BAU: Use the local signed trust anchor file in verify-metadata

configuration/hub/saml-engine.yml, configuration/hub/saml-proxy.yml, configuration/hub/saml-soap-proxy.yml
SAML Engine, SAML SOAP Proxy and SAML Proxy will use
TrustStoreBackedMetadataConfiguration instead of
TrustStorePathMetadataConfiguration. These changes require
trustStore.path and trustStore.password to be added to their config
files.
Co-authored-by: Rachel Smith
<rachel.smith@digital.cabinet-office.gov.uk>
Co-authored-by: Kornelis Sietsma
<kornelis.sietsma@digital.cabinet-office.gov.uk>
=> BAU: Add trustStore.path and its password

configuration/hub/config.yml
this is being introduced to try and keep verify-local-startup up to date with the local config needed in ida-hub-acceptance-tests
=> CTV-180 add translationDirectory to local config

generate/fed-config.rb, generate/generate-metadata.sh
**What**
This PR updates the scripts responsible for generating config data (for running the hub locally), so as to also generate the translation files needed by the hub.
As a background, translation files are needed by the hub (aka config service), which exposes a new end-point for fetching translations. The path to translation files is defined within `configuration/hub/config.yml`, under key `translationsDirectory`.
**Who should review this PR**
* Anyone part of the Connecting team involved in the implementation of translations endpoint for Config service.
* Anyone in the core team.
=> Update scripts responsible for generating config data to also generate translation files

config/ports.env
-This will allow eidas journey to work when starting hub
through ida-hub-acceptance-test
-Please also refer to ida-hub-acceptance-test PR
=> Bau - Add eidasEnabled variable value

configuration/hub/policy.yml, configuration/hub/saml-proxy.yml, configuration/hub/saml-soap-proxy.yml
We no longer use the KMS to store the encryption key
=> Add event emitter encryption key config

configuration/hub/saml-engine.yml
Since https://github.com/alphagov/verify-hub/pull/122 SAML Engine doesn't need these certs. Remove them.
=> BAU: Remove hub certs from SAML Engine

configuration/hub/policy.yml, configuration/hub/saml-proxy.yml, configuration/hub/saml-soap-proxy.yml
Event Emitter now sends events to the API Gateway and not directly to the SQS queue.
Instead of sending directly to the SQS queue each event will now go through an API gateway
https://trello.com/c/auJ7kBAx/120-upgrade-event-emitter-library-in-hub
Co-authored-by: dbes_gds daniel.besbrode@digital.cabinet-office.gov.uk
=> TRELLO-auJ7kBAx: Remove SQS queue from Event Emitter configuration 

generate/pki.rb
- When generating keys with the new script, the RSA section was lost so
cfssl was generating _some other_ kind of key
=> BAU: Make sure we generate RSA keys

lib/services.sh
ida-hub-acceptance-tests#92 introduced the use of `set -e` for
aborting when commands unexpectedly fail.
However, start_service_checker had a curl command which was expected
to fail, at least until the service comes up.  Therefore, `set -e`
caused start_service_checker to bomb out if curl ever failed.
This commit changes the function to run curl inside an `if` block,
which causes bash not to abort under `set -e` if curl fails.
I happen to think that the if block is more readable than the
`&& break || sleep 5` thing that it replaced, too. :)
=> make start_service_checker work under `set -e`

configuration/stub-frontend-fed-config/locales/rps/test-rp-no-ab-test.yml, configuration/stub-frontend-fed-config/locales/rps/test-rp-no-demo.yml, configuration/stub-frontend-fed-config/locales/rps/test-rp-noc3.yml, configuration/stub-frontend-fed-config/locales/rps/test-rp-non-eidas.yml, configuration/stub-frontend-fed-config/locales/rps/test-rp-repudiation.yml, configuration/stub-frontend-fed-config/locales/rps/test-rp-with-continue-on-fail.yml, configuration/stub-frontend-fed-config/locales/rps/test-rp.yml, generate/fed-config.rb
Renaming test-rp name "register for an identity" profile to "test GOV.UK Verify user journeys" to make the content more readable.
=> FIREBREAK: Rename test-rp

Dockerfile
If we use --no-cache, apk won't save package lists to disk. This results in
slightly smaller images.
=> BAU: Use --no-cache with apk to have smaller images

configuration/stub-frontend-fed-config/identity_providers.yml
Remove a file no longer used - the config has been moved to verify-hub-federation-config instead
See https://trello.com/c/ly1m24h4/42-communicate-to-users-when-idp-is-having-technical-difficulty
=> ly1m24h4: remove unused file

generate-env.rb
Verify Stub IDP failed to connect to its PostgreSQL database due to a missing password. This change adds a password to fix the database connection error. This change is needed because Verify Stub IDP's startup script specifies the password for its database (source: https://github.com/alphagov/verify-stub-idp/blob/a401e5185a07d280ec368225f37a653c59fe1b0e/startup.sh#L22).
Author: @adityapahuja
=> BAU: Fix Verify Stub IDP's DB connection failure

Dockerfile, build-local.rb, docker-compose.yml, startup.sh
Sometimes the integration tests will fail when building SAML-Soap-proxy and SAML-proxy.  This seems to be due to a bottle next in available system resources when this first tries to build.  Attempting to run startup again most times seems to result in a successful build.  So these changes attempt to retry the build if it fails so the user doesn't have to.
This also includes the Fixes for moving everything to GHCR
=> Introduce retries to the build script

Dockerfile, docker-compose.yml
So looks like verify-local-startup has been broken for a few days.  This PR should fix any issue people are having.  Fixes include:
* Update XMLSecTool to version 3.0
* Fixed the docker-compose which was trying to pull down the wrong postgresql image
⚠ This PR is important to merge in quickly as peoples verify-local-startup will be broken until its applied.
=> ⚠ BAU Fix broken verify-local-startup

.dockerignore, Dockerfile, config/bashrc
This work was done to create an image which could be used interactively to run xmlsectool.  Update also includes bumping the Java version to version 11.
=> BAU Make xmlsectool a command

generate/generate-metadata.sh
The stable version of XMLSecTool is now version 3.0.0 and the old version 2.0.0 has been deprecated.  This just updates a reference to the old version.
=> BAU wrong xmlsectool version referenced in script

generate/generate-metadata.sh
XMLSecTool was recently updated to version 3.0.0 and we've updated our use of the tool to version 3.0.0.  Version 3.0.0 of the tool deprecated the use of `--key` infavour of `--keyFile`.  This PR fixes our use of the tool to prevent the warning.
=> BAU Fix deprecation warning from XMLSecTool

lib/components.rb
This PR fixes a pair of bugs in the component script.  The first is where a component which has never been run is incorrectly reported as missing when in fact its just not been run yet.  The second bug affects the rebuild process which was showing starting component when the logic says don't run if the component wasn't running to begin with.  Also it now shows a hint in the rebuild process that to start the rebuilt but stopped component run the script with the -s <component> option.
=> BUGFIX Fixes a pair of bugs which have been found in the component script

lib/components.rb
There was a syntax error in the rebuild function preventing it from running.  This fixes that issue.
=> BUGFIX Fixed broken rebuild function

generate/generate-metadata.sh
This updates the generate-metadata script to correctly test if
xmlsectool is already installed and use it, if the XMLSECTOOL env
variable isn't set.
This allows you to run the script locally, not in a container where the
env var is set for you.
=> BAU: Allow use of preinstalled xmlsectool

Dockerfile, docker-compose.yml
We're no longer using github container registry and are now using docker
hub again.
Signed-off-by: Chris Mills <7100370+chriscoffee@users.noreply.github.com>
=> [HUB-841] Use docker hub rather than ghcr

Dockerfile, lib/image_builder.rb
This commit fixes two critical bugs in verify-local-startup.  These are:
* The recent change in to the Dockerfile to Go 16 causes one of the
components to fail to build.  Fix: Switched back to using Go 15 fixes
the issue
* When a build fails or logging was turned on the build would fail
because lib/logs didn't exist.  Fix: updated the path to point to the
original log directory logs/
=> BAU Fix critical bugs in local-startup

lib/build-local.rb, lib/image_builder.rb, startup.sh
Often when developing the hub we want to use a snapshot of another
dependency, which has been published to your local maven repo.
This change makes your local maven repo available in the docker builds.
It copies the repo with a namespace to avoid issues with multiple
threads.
It adds `COPY` lines to the Dockerfile on the fly, rather than having to
maintain a separate Dockerfile.
I have no idea if this works with Linux so thoughts more than welcome.
=> BAU: Allow using SNAPSHOTS in maven local

Gemfile, Gemfile.lock, components.sh, lib/build-local.rb, lib/components.rb, lib/image_builder.rb, lib/logger.rb, startup.sh
This is quite a far reaching PR as it fixes a couple of bugs and introduces logging in to the build-local ruby script and associate
components.  The bugs which are fixed are:
* Success of Fail bug (issue #89) - where the script would report a successful build on a component despite the actual command failing
* Correctly report number physical cpus when assigning the default number of threads.  This is now set to the maximum phyical cpu count. (unreported but known) 
* Fixes the components script which was broken with the introduction of the mavel build option. (unreported but known)
=> Fix for issue #89 success on fail bug

lib/build-local.rb, lib/components.rb
The use of /dev/null is good for Linux and Mac systems but its bad for Windows.  So I have updated the reference to /dev/null to point to File::NULL instead.  Which is platform independent.
=> BAU Fix for using posix /dev/null for null device

Dockerfile
- Cloudflare cfssl now requires Go 1.16+ to build otherwise verify-local-startup does not work
- 'Go get' has been deprecated and we should now use 'Go install'
=> BAU - Uplift golang to 1.19.0 to fix local startup
